### ISSUE TITLE
Allow adding tags for CloudFormation stack

### ISSUE THREAD

**Issue by jsyrjala** [NitorCreations/nitor-deploy-tools#14]
Allow specifying tags for CloudFormation stack. Tags should be given as `--tags` parameter for [create-stack](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-stack.html) and [update-stack](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/update-stack.html) commands.

**Comment by psiniemi** [comment]
Tags implemented, see https://github.com/NitorCreations/nitor-deploy-tools/blob/master/docs/template-processing.md#tags
